USE [master]
GO

-- Método 1:
EXEC sp_attach_single_file_db @dbname= NOMEBANCO_REC
@physname=N'C:\NOMEBANCO.mdf'
GO

-- Método 2:
CREATE DATABASE NOMEBANCO ON
(FILENAME = N'C:\NOMEBANCO.mdf')
FOR ATTACH_REBUILD_LOG
GO

-- Método 3:
CREATE DATABASE NOMEBANCO
(FILENAME =N'C:\NOMEBANCO.mdf')

-- Métoda 4:
USE [master]
GO
CREATE DATABASE [NOMEBANCO] ON 
( FILENAME = N'C:\NOMEBANCO.mdf' )
 FOR ATTACH_FORCE_REBUILD_LOG  
GO 

--limpa arquivodelog
select * from sysfiles

USE NOMEBANCO;
GO
ALTER DATABASE NOMEBANCO SET RECOVERY SIMPLE;
GO
DBCC SHRINKFILE ('NOMEBANCO_log', 1);
GO
ALTER DATABASE NOMEBANCO
SET RECOVERY FULL;
GO