CREATE FUNCTION [dbo].[FN_FORMATAR_TEXTO]
(
    @TEXTO VARCHAR(MAX)
)
RETURNS VARCHAR(MAX)
AS
BEGIN
 
    DECLARE @TEXTO_FORMATADO VARCHAR(MAX)
     
    SET @TEXTO_FORMATADO = UPPER(@TEXTO)
        COLLATE sql_latin1_general_cp1250_ci_as
 
    SET @TEXTO_FORMATADO = @TEXTO_FORMATADO
        COLLATE sql_latin1_general_cp1251_ci_as
 
    RETURN @TEXTO_FORMATADO
 
END
GO



SELECT * INTO Produto_BK FROM Produto
go
UPDATE PRODUTO SET NOME = LTRIM(RTRIM(NOME))
go
UPDATE PRODUTO SET NOME = DBO.FN_FORMATAR_TEXTO(NOME)
go