
ALTER DATABASE BANCO SET EMERGENCY

ALTER DATABASE BANCO SET SINGLE_USER

DBCC CHECKDB (BANCO, repair_allow_data_loss ) WITH ALL_ERRORMSGS

ALTER DATABASE BANCO SET read_write

ALTER DATABASE BANCO SET multi_user